version: 2
updates:
  # Update to newer version of GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Update to newer NuGet dependencies
  - package-ecosystem: "nuget"
    directories:
      - "/Fesh.Revit.Bootstrapper"
      - "/Fesh.Revit"
    schedule:
      interval: "daily"

