version: 2
updates:
  # Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Update NuGet dependencies
  - package-ecosystem: "nuget"
    directories:
      - "/Fesh.Revit.Bootstrapper/"
      - "/Fesh.Revit/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "Autodesk.Revit.SDK"

