name: Dependabot for Nuget dependencies and Github Actions
version: 2
updates:
  # Update to newer version of GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Update to newer NuGet dependencies
  - package-ecosystem: "nuget"
    directory: "./Fesh.Revit/"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "./Fesh.Revit.Bootstrapper/"
    schedule:
      interval: "daily"

